#!/usr/bin/env python3
from typing import List


def solve(c: List[str]) -> str:
    res = ""
    for i in range(3):
        res += c[i][i]
    return res


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    # failed to analyze input format
    c = [input() for _ in range(3)]
    a = solve(c)
    print(a)


if __name__ == "__main__":
    main()
